import os
import re
import glob

def main():
    output_file = 'src/zeon.zig'

    content = [
        "// AUTO-GENERATED API FILE. DO NOT EDIT DIRECTLY.",
        "// Generated by scripts/generate_api.py\n",
        "pub const arch = @import(\"arch.zig\");",
        "pub const common = @import(\"common.zig\");",
        "pub const types = @import(\"types.zig\");\n"
    ]

    test_imports = [
        "    _ = @import(\"types.zig\");",
        "    _ = @import(\"common.zig\");",
        "    _ = @import(\"arch.zig\");"
    ]

    with open('src/types.zig', 'r') as f:
        types_code = f.read()
        type_matches = re.findall(r'pub\s+const\s+([a-zA-Z0-9_]+)\s*=', types_code)

        for t in sorted(set(type_matches)):
            content.append(f'pub const {t} = types.{t};')

    intrinsic_files = glob.glob('src/intrinsics/*.zig')
    for file_path in sorted(intrinsic_files):
        module_name = os.path.basename(file_path).replace('.zig', '')

        test_imports.append(f'    _ = @import(\"intrinsics/{module_name}.zig\");')

        with open(file_path, 'r') as f:
            file_code = f.read()
            fn_matches = re.findall(r'pub\s+inline\s+fn\s+(v[a-zA-Z0-9_]+)\s*\(', file_code)

            if fn_matches:
                for fn_name in sorted(set(fn_matches)):
                    content.append(f'pub const {fn_name} = @import("intrinsics/{module_name}.zig").{fn_name};')

    content.append("\ntest {")
    content.extend(test_imports)
    content.append("}\n")

    with open(output_file, 'w') as f:
        f.write('\n'.join(content))

    print(f"Generated {output_file}")

if __name__ == '__main__':
    main()
