#!/usr/bin/env python3
"""
API Generator for Zeon (ARM NEON SIMD library for Zig).

Scans `src/types.zig` and `src/intrinsics/*.zig` to automatically generate `src/zeon.zig`.
"""

import argparse
import os
import re
import sys
from pathlib import Path


def get_project_root() -> Path:
    """Returns the repository root directory."""
    return Path(__file__).resolve().parent.parent


def extract_types(types_file: Path) -> list[str]:
    """Extract all `pub const <Name> =` definitions from types.zig."""
    content = types_file.read_text(encoding="utf-8")
    matches = re.findall(r"^pub\s+const\s+([a-zA-Z0-9_]+)\s*=", content, re.MULTILINE)
    return sorted(set(matches))


def extract_intrinsics(module_file: Path) -> list[str]:
    """Extract all `pub [inline] fn <name>(` definitions from an intrinsic module."""
    content = module_file.read_text(encoding="utf-8")
    matches = re.findall(r"pub\s+(?:inline\s+)?fn\s+(v[a-zA-Z0-9_]+)\s*\(", content)
    return sorted(set(matches))


def generate_api_content(root_dir: Path) -> tuple[str, dict]:
    """Generate the full content of src/zeon.zig and return generation metrics."""
    types_file = root_dir / "src" / "types.zig"
    intrinsics_dir = root_dir / "src" / "intrinsics"

    if not types_file.is_file():
        raise FileNotFoundError(f"Missing types file: {types_file}")
    if not intrinsics_dir.is_dir():
        raise FileNotFoundError(f"Missing intrinsics directory: {intrinsics_dir}")

    lines: list[str] = [
        "// AUTO-GENERATED API FILE. DO NOT EDIT DIRECTLY.",
        "// Generated by scripts/generate_api.py",
        "",
        'pub const arch = @import("arch.zig");',
        'pub const common = @import("common.zig");',
        'pub const types = @import("types.zig");',
        "",
    ]

    # Submodule namespaces (allows `zeon.arithmetic.vaddq_f32`)
    lines.append("// Submodule Namespaces")
    intrinsic_files = sorted(intrinsics_dir.glob("*.zig"))
    for f in intrinsic_files:
        mod_name = f.stem
        lines.append(f'pub const {mod_name} = @import("intrinsics/{mod_name}.zig");')
    lines.append("")

    # Vector Types re-export
    exported_types = extract_types(types_file)
    lines.append(f"// Vector Types ({len(exported_types)})")
    for t in exported_types:
        lines.append(f"pub const {t} = types.{t};")
    lines.append("")

    # Intrinsics grouped by category
    test_imports = [
        '    _ = @import("types.zig");',
        '    _ = @import("common.zig");',
        '    _ = @import("arch.zig");',
    ]

    seen_intrinsics: dict[str, str] = {}
    stats: dict = {
        "types": len(exported_types),
        "modules": len(intrinsic_files),
        "intrinsics": 0,
        "per_module": {},
    }

    for f in intrinsic_files:
        mod_name = f.stem
        fns = extract_intrinsics(f)
        stats["per_module"][mod_name] = len(fns)
        stats["intrinsics"] += len(fns)
        test_imports.append(f'    _ = @import("intrinsics/{mod_name}.zig");')

        if fns:
            title = mod_name.replace("_", " ").title()
            lines.append(f"// {title} Intrinsics ({len(fns)})")
            for fn_name in fns:
                if fn_name in seen_intrinsics:
                    prev = seen_intrinsics[fn_name]
                    raise ValueError(
                        f"Duplicate intrinsic '{fn_name}' found in '{mod_name}.zig' "
                        f"(already defined in '{prev}.zig')"
                    )
                seen_intrinsics[fn_name] = mod_name
                lines.append(f'pub const {fn_name} = @import("intrinsics/{mod_name}.zig").{fn_name};')
            lines.append("")

    # Root test aggregator
    lines.append("test {")
    lines.extend(test_imports)
    lines.append("}")
    lines.append("")

    return "\n".join(lines), stats


def main():
    parser = argparse.ArgumentParser(description="Generate src/zeon.zig API exports.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check whether src/zeon.zig is up-to-date without modifying it (exits with code 1 if outdated).",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="Suppress output unless errors occur.",
    )
    parser.add_argument(
        "-f",
        "--force",
        action="store_true",
        help="Force writing even if content is unchanged.",
    )
    args = parser.parse_args()

    root_dir = get_project_root()
    output_file = root_dir / "src" / "zeon.zig"

    try:
        new_content, stats = generate_api_content(root_dir)
    except Exception as e:
        sys.stderr.write(f"Error generating API: {e}\n")
        sys.exit(1)

    is_different = True
    if output_file.is_file():
        existing_content = output_file.read_text(encoding="utf-8")
        is_different = existing_content != new_content

    if args.check:
        if is_different:
            sys.stderr.write("src/zeon.zig is outdated! Run `python3 scripts/generate_api.py` to regenerate.\n")
            sys.exit(1)
        else:
            if not args.quiet:
                print("src/zeon.zig is up-to-date.")
            sys.exit(0)

    if not is_different and not args.force:
        if not args.quiet:
            print(
                f"src/zeon.zig is already up-to-date ({stats['intrinsics']} intrinsics across {stats['modules']} modules, {stats['types']} types)."
            )
        return

    output_file.write_text(new_content, encoding="utf-8")

    if not args.quiet:
        print(f"Generated {output_file.relative_to(root_dir)}:")
        print(f"  Total Intrinsics : {stats['intrinsics']}")
        print(f"  Vector Types     : {stats['types']}")
        print(f"  Modules          : {stats['modules']}")
        for mod, count in sorted(stats["per_module"].items()):
            print(f"    - {mod:14s}: {count:4d} functions")


if __name__ == "__main__":
    main()
