//! # Wave Equation & Interference Simulation (ARM NEON)
//!
//! An animated 30 FPS terminal visualizer simulating multi-source wave interference
//! and dynamic color field modulation using 4-way SIMD floating-point operations.
//!
//! ### Technique:
//! - Evaluates 4 adjacent spatial grid cells per SIMD step using NEON registers (`f32x4`).
//! - Accumulates interference patterns from multiple dynamic wave centers with `vaddq_f32` and `vmulq_n_f32`.
//! - Evaluates radial distance falloff and glow intensity clamped via `vmaxq_f32` and `vminq_f32`.
//! - Modulates RGB color palette channels concurrently using vector-vector multiplies (`vmulq_f32`).

const std = @import("std");
const neon = @import("zeon");

const WIDTH: usize = 84;
const HEIGHT: usize = 32;
const LANES: usize = 4;

const FPS: u64 = 30;
const FRAME_NS: u64 = std.time.ns_per_s / FPS;
const DURATION_SECONDS: f32 = 18.0;

const TAU: f32 = 6.283185307179586;

/// 24-bit RGB pixel color representation.
const Cell = struct {
    r: u8,
    g: u8,
    b: u8,
};

/// Clamps scalar float `x` to range [0.0, 1.0].
fn clamp01(x: f32) f32 {
    return @max(0.0, @min(1.0, x));
}

/// Evaluates a smooth, cyclic RGB cosine color palette based on normalized parameter `t_in`.
///
/// ### Cosine Color Gradients (Inigo Quilez technique):
/// Colors are generated by computing 3 out-of-phase sine waves offset by 120 degrees (TAU/3):
/// - Red:   `0.5 + 0.5 * sin(TAU * (t + 0.0000))`
/// - Green: `0.5 + 0.5 * sin(TAU * (t + 0.3333))`
/// - Blue:  `0.5 + 0.5 * sin(TAU * (t + 0.6666))`
/// This guarantees continuous, harmonious color transitions across all wave phases.
fn palette(t_in: f32) Cell {
    var t = t_in;

    // Wrap parameter t into [0.0, 1.0)
    while (t < 0.0) t += 1.0;
    while (t >= 1.0) t -= 1.0;

    const r_wave = 0.5 + 0.5 * @sin(TAU * (t + 0.0000));
    const g_wave = 0.5 + 0.5 * @sin(TAU * (t + 0.3333));
    const b_wave = 0.5 + 0.5 * @sin(TAU * (t + 0.6666));

    return .{
        .r = @intFromFloat(clamp01(r_wave) * 255.0),
        .g = @intFromFloat(clamp01(g_wave) * 255.0),
        .b = @intFromFloat(clamp01(b_wave) * 255.0),
    };
}

/// Appends a raw byte slice to an in-memory frame buffer, checking for bounds overflow.
fn push(bytes: []u8, at: *usize, s: []const u8) !void {
    if (at.* + s.len > bytes.len) {
        return error.FrameBufferFull;
    }

    @memcpy(bytes[at.* .. at.* + s.len], s);
    at.* += s.len;
}

/// Formats and appends an ANSI escape string into the frame buffer.
fn pushFmt(
    bytes: []u8,
    at: *usize,
    comptime fmt: []const u8,
    args: anytype,
) !void {
    const out = std.fmt.bufPrint(bytes[at.*..], fmt, args) catch {
        return error.FrameBufferFull;
    };

    at.* += out.len;
}

/// Evaluates physics and visual properties for 4 adjacent screen pixels simultaneously
/// using ARM NEON 128-bit vector arithmetic (`f32x4`).
///
/// ### Simulation Pipeline:
/// 1. **Wave Interference**: Superimposes 4 distinct harmonic wave patterns:
///    - Horizontal plane wave: $W_a = \sin(4.2x + 1.7t)$
///    - Vertical plane wave:   $W_b = \sin(5.1y - 1.2t)$
///    - Diagonal plane wave:   $W_c = \sin(3.7(x + y) + 0.9t)$
///    - Circular ripple wave:  $W_d = \sin(10.0 \cdot r - 2.4t)$
/// 2. **Vector Superposition**: Sums all 4 waves and normalizes the sum to [0.0, 1.0]
///    using `vaddq_f32`, `vmulq_n_f32`, and offset addition.
/// 3. **Radial Ambient Glow**: Computes quadratic falloff $1.0 - 0.45 \cdot r^2$ clamped at 0.0
///    using `vmulq_n_f32`, `vsubq_f32`, and `vmaxq_f32`.
/// 4. **Composite Brightness**: Blends wave amplitude (72%) with ambient glow (45%) and clamps
///    to [0.0, 1.0] using vector min/max (`vminq_f32`, `vmaxq_f32`).
/// 5. **Vector Shading**: Scales each color channel (Red, Green, Blue) across all 4 pixels
///    using `vmulq_f32`.
fn render4(
    fx: *const [LANES]f32,
    fy: f32,
    t: f32,
    output_r: *[LANES]f32,
    output_g: *[LANES]f32,
    output_b: *[LANES]f32,
) void {
    var wave_a: [LANES]f32 = undefined;
    var wave_b: [LANES]f32 = undefined;
    var wave_c: [LANES]f32 = undefined;
    var wave_d: [LANES]f32 = undefined;
    var radii_sq: [LANES]f32 = undefined;

    // Step 1: Harmonic Wave Source Generation
    for (0..LANES) |i| {
        const x = fx.*[i];

        wave_a[i] = @sin(x * 4.2 + t * 1.7);
        wave_b[i] = @sin(fy * 5.1 - t * 1.2);
        wave_c[i] = @sin((x + fy) * 3.7 + t * 0.9);

        const radius_sq = x * x + fy * fy;
        radii_sq[i] = radius_sq;

        wave_d[i] = @sin(@sqrt(radius_sq) * 10.0 - t * 2.4);
    }

    // Step 2: Vector Load into 128-bit NEON Registers
    // Each register holds 4 floating-point values corresponding to adjacent screen pixels:
    // va = [ wave_a[0], wave_a[1], wave_a[2], wave_a[3] ]
    const va = neon.vld1q_f32(&wave_a);
    const vb = neon.vld1q_f32(&wave_b);
    const vc = neon.vld1q_f32(&wave_c);
    const vd = neon.vld1q_f32(&wave_d);

    // Step 3: Vector Superposition of Wave Fields
    // wave = (a + b + c + d) * 0.125 + 0.5
    // Sums the 4 wave harmonics across all 4 vector lanes in parallel.
    var wave = neon.vaddq_f32(va, vb);
    wave = neon.vaddq_f32(wave, vc);
    wave = neon.vaddq_f32(wave, vd);
    // Multiply by 0.125 (divides by 8, mapping range [-4.0, 4.0] to [-0.5, 0.5])
    wave = neon.vmulq_n_f32(wave, 0.125);
    // Offset by +0.5 to center into range [0.0, 1.0]
    wave = neon.vaddq_f32(wave, neon.vmovq_n_f32(0.5));

    // Step 4: Compute Radial Ambient Glow
    // glow = max(1.0 - radius² * 0.45, 0.0)
    // Darkens pixels further away from the screen center.
    var glow = neon.vmulq_n_f32(neon.vld1q_f32(&radii_sq), 0.45);
    glow = neon.vsubq_f32(neon.vmovq_n_f32(1.0), glow);
    // Vector max clamps values below 0.0 to 0.0 across all 4 lanes
    glow = neon.vmaxq_f32(glow, neon.vmovq_n_f32(0.0));

    // Step 5: Compute Final Pixel Brightness (Value)
    // value = clamp(wave * 0.72 + glow * 0.45, 0.0, 1.0)
    var value = neon.vmulq_n_f32(wave, 0.72);
    value = neon.vaddq_f32(value, neon.vmulq_n_f32(glow, 0.45));
    // Vector clamp: max with 0.0, then min with 1.0
    value = neon.vmaxq_f32(value, neon.vmovq_n_f32(0.0));
    value = neon.vminq_f32(value, neon.vmovq_n_f32(1.0));

    // Extract computed wave and value arrays to sample color palette
    var wave_values: [LANES]f32 = undefined;
    var value_values: [LANES]f32 = undefined;
    neon.vst1q_f32(&wave_values, wave);
    neon.vst1q_f32(&value_values, value);

    // Step 6: Sample Palette Colors
    var r_palette: [LANES]f32 = undefined;
    var g_palette: [LANES]f32 = undefined;
    var b_palette: [LANES]f32 = undefined;

    for (0..LANES) |i| {
        const radius = @sqrt(radii_sq[i]);
        const color = palette(wave_values[i] + t * 0.035 + radius * 0.12);

        r_palette[i] = @floatFromInt(color.r);
        g_palette[i] = @floatFromInt(color.g);
        b_palette[i] = @floatFromInt(color.b);
    }

    // Step 7: Vector RGB Shading Modulation
    // Multiplies the raw 0..255 palette color channels by the computed brightness value:
    //   RGB = palette * value
    // Executed as 3 vector multiplications (4 pixels per multiplication = 12 channels shaded)
    const red = neon.vmulq_f32(neon.vld1q_f32(&r_palette), value);
    const green = neon.vmulq_f32(neon.vld1q_f32(&g_palette), value);
    const blue = neon.vmulq_f32(neon.vld1q_f32(&b_palette), value);

    // Write final floating-point color channels to output pointers
    neon.vst1q_f32(output_r, red);
    neon.vst1q_f32(output_g, green);
    neon.vst1q_f32(output_b, blue);
}

pub fn main(init: std.process.Init) !void {
    // Pre-allocated in-memory frame buffer (~180 KB).
    // Writing the full screen frame into memory first and flushing to stdout with
    // a single writeStreamingAll call eliminates terminal flickering and tearing.
    var frame: [180 * 1024]u8 = undefined;

    // Step 1: Terminal Initialization
    // - \x1b[?1049h: Switch to alternate screen buffer (preserves terminal scrollback)
    // - \x1b[2J:    Clear entire screen
    // - \x1b[H:     Move cursor to home position (row 1, col 1)
    // - \x1b[?25l:  Hide cursor to prevent blinking artifacts during rendering
    var setup_len: usize = 0;
    try push(
        &frame,
        &setup_len,
        "\x1b[?1049h\x1b[2J\x1b[H\x1b[?25l",
    );
    try std.Io.File.stdout().writeStreamingAll(
        init.io,
        frame[0..setup_len],
    );

    // Step 2: Cleanup Hook (Guaranteed on Exit)
    // - \x1b[0m:    Reset all colors and text formatting
    // - \x1b[?25h:  Restore cursor visibility
    // - \x1b[?1049l: Exit alternate screen buffer back to normal user shell
    defer {
        var restore: [64]u8 = undefined;
        const restore_text = std.fmt.bufPrint(
            &restore,
            "\x1b[0m\x1b[?25h\x1b[?1049l\n",
            .{},
        ) catch unreachable;

        std.Io.File.stdout().writeStreamingAll(
            init.io,
            restore_text,
        ) catch {};
    }

    var t: f32 = 0.0;
    var frames: u64 = 0;

    const total_frames: u64 = @intFromFloat(
        DURATION_SECONDS * @as(f32, @floatFromInt(FPS)),
    );

    // Step 3: Main 30 FPS Animation Loop
    while (frames < total_frames) {
        // High-precision start timestamp for frame pacing
        const frame_start = std.Io.Timestamp.now(init.io, .awake);

        var len: usize = 0;

        // Reposition cursor to top-left (home) instead of clearing screen
        try push(
            &frame,
            &len,
            "\x1b[H",
        );

        // Render each row of the terminal display
        for (0..HEIGHT) |y| {
            // Map vertical row [0, HEIGHT-1] to normalized coordinates [-1.0, 1.0]
            const fy: f32 =
                (@as(f32, @floatFromInt(y)) /
                    @as(f32, @floatFromInt(HEIGHT - 1))) *
                2.0 -
                1.0;

            var x: usize = 0;

            // SIMD Vectorized Pixel Processing (4 Pixels per Step)
            while (x + LANES <= WIDTH) : (x += LANES) {
                var fx: [LANES]f32 = undefined;

                // Map 4 adjacent horizontal pixels to normalized coordinates [-1.0, 1.0]
                for (0..LANES) |lane| {
                    const px = x + lane;
                    fx[lane] =
                        (@as(f32, @floatFromInt(px)) /
                            @as(f32, @floatFromInt(WIDTH - 1))) *
                        2.0 -
                        1.0;
                }

                var red_values: [LANES]f32 = undefined;
                var green_values: [LANES]f32 = undefined;
                var blue_values: [LANES]f32 = undefined;

                // Evaluate 4-pixel wave superposition and RGB shading in NEON
                render4(
                    &fx,
                    fy,
                    t,
                    &red_values,
                    &green_values,
                    &blue_values,
                );

                // Format each pixel using 24-bit ANSI TrueColor background sequence:
                //   \x1b[48;2;R;G;Bm <space>
                for (0..LANES) |lane| {
                    const red: u8 = @intFromFloat(
                        @max(0.0, @min(255.0, red_values[lane])),
                    );
                    const green: u8 = @intFromFloat(
                        @max(0.0, @min(255.0, green_values[lane])),
                    );
                    const blue: u8 = @intFromFloat(
                        @max(0.0, @min(255.0, blue_values[lane])),
                    );

                    try pushFmt(
                        &frame,
                        &len,
                        "\x1b[48;2;{d};{d};{d}m ",
                        .{ red, green, blue },
                    );
                }
            }

            // Scalar Remainder Tail (for widths not divisible by 4)
            while (x < WIDTH) : (x += 1) {
                const fx: f32 =
                    (@as(f32, @floatFromInt(x)) /
                        @as(f32, @floatFromInt(WIDTH - 1))) *
                    2.0 -
                    1.0;

                const red_wave = @sin(fx * 4.2 + t * 1.7);
                const blue_wave = @sin(fy * 5.1 - t * 1.2);
                const diagonal_wave = @sin((fx + fy) * 3.7 + t * 0.9);

                const radius_sq = fx * fx + fy * fy;
                const radius = @sqrt(radius_sq);
                const radial_wave = @sin(radius * 10.0 - t * 2.4);

                const wave = (red_wave + blue_wave + diagonal_wave + radial_wave) * 0.125 + 0.5;
                const glow = clamp01(1.0 - radius * 0.9);
                const value = clamp01(wave * 0.72 + glow * 0.45);

                const rgb = palette(wave + t * 0.035 + radius * 0.12);

                const red: u8 = @intFromFloat(@as(f32, @floatFromInt(rgb.r)) * value);
                const green: u8 = @intFromFloat(@as(f32, @floatFromInt(rgb.g)) * value);
                const blue: u8 = @intFromFloat(@as(f32, @floatFromInt(rgb.b)) * value);

                try pushFmt(
                    &frame,
                    &len,
                    "\x1b[48;2;{d};{d};{d}m ",
                    .{ red, green, blue },
                );
            }

            // End row and return to start of next line
            try push(
                &frame,
                &len,
                "\x1b[0m\r\n",
            );
        }

        // Step 4: Display Status Header & Metrics
        try pushFmt(
            &frame,
            &len,
            "\x1b[0m\nframe {d:0>5}   {d}x{d} @ {d} FPS\n",
            .{
                frames,
                WIDTH,
                HEIGHT,
                FPS,
            },
        );

        // Single atomic flush of the complete frame buffer to terminal output
        try std.Io.File.stdout().writeStreamingAll(
            init.io,
            frame[0..len],
        );

        // Step 5: Frame Pacing and Dynamic Sleep
        // Target 30 FPS: sleep remaining time in frame budget (33.33ms)
        const frame_end = std.Io.Timestamp.now(init.io, .awake);
        const elapsed_duration = frame_start.durationTo(frame_end);
        const elapsed_ns = elapsed_duration.toNanoseconds();

        if (elapsed_ns < FRAME_NS) {
            try init.io.sleep(
                .fromNanoseconds(FRAME_NS - elapsed_ns),
                .awake,
            );
        }

        // Advance simulation time parameter
        t += 1.0 / @as(f32, @floatFromInt(FPS));
        frames += 1;
    }
}
test "clamp01 clamps below zero" {
    try std.testing.expectEqual(@as(f32, 0.0), clamp01(-1.0));
}

test "clamp01 clamps above one" {
    try std.testing.expectEqual(@as(f32, 1.0), clamp01(2.0));
}

test "clamp01 preserves values in range" {
    try std.testing.expectEqual(@as(f32, 0.0), clamp01(0.0));
    try std.testing.expectEqual(@as(f32, 0.5), clamp01(0.5));
    try std.testing.expectEqual(@as(f32, 1.0), clamp01(1.0));
}

test "palette wraps values below zero" {
    const a = palette(-0.25);
    const b = palette(0.75);

    try std.testing.expectEqual(a.r, b.r);
    try std.testing.expectEqual(a.g, b.g);
    try std.testing.expectEqual(a.b, b.b);
}

test "palette wraps values above one" {
    const a = palette(1.25);
    const b = palette(0.25);

    try std.testing.expectEqual(a.r, b.r);
    try std.testing.expectEqual(a.g, b.g);
    try std.testing.expectEqual(a.b, b.b);
}

test "palette produces valid RGB values" {
    const samples = [_]f32{
        0.0,
        0.125,
        0.25,
        0.5,
        0.75,
        0.999,
    };

    for (samples) |sample| {
        const color = palette(sample);

        // u8 already guarantees the range, but explicitly exercise
        // every generated channel.
        try std.testing.expect(color.r >= 0);
        try std.testing.expect(color.g >= 0);
        try std.testing.expect(color.b >= 0);
    }
}

test "push appends bytes" {
    var buffer: [32]u8 = undefined;
    var len: usize = 0;

    try push(&buffer, &len, "hello");
    try push(&buffer, &len, " world");

    try std.testing.expectEqual(@as(usize, 11), len);
    try std.testing.expectEqualStrings(
        "hello world",
        buffer[0..len],
    );
}

test "push detects buffer overflow" {
    var buffer: [4]u8 = undefined;
    var len: usize = 0;

    try std.testing.expectError(
        error.FrameBufferFull,
        push(&buffer, &len, "hello"),
    );

    try std.testing.expectEqual(@as(usize, 0), len);
}

test "pushFmt formats into framebuffer" {
    var buffer: [64]u8 = undefined;
    var len: usize = 0;

    try pushFmt(
        &buffer,
        &len,
        "rgb={d},{d},{d}",
        .{ 12, 34, 56 },
    );

    try std.testing.expectEqualStrings(
        "rgb=12,34,56",
        buffer[0..len],
    );
}

test "pushFmt detects buffer overflow" {
    var buffer: [4]u8 = undefined;
    var len: usize = 0;

    try std.testing.expectError(
        error.FrameBufferFull,
        pushFmt(
            &buffer,
            &len,
            "value={d}",
            .{12345},
        ),
    );
}

test "zeon vector add works for wave lanes" {
    const a: [LANES]f32 = .{
        1.0,
        2.0,
        3.0,
        4.0,
    };

    const b: [LANES]f32 = .{
        10.0,
        20.0,
        30.0,
        40.0,
    };

    const va = neon.vld1q_f32(&a);
    const vb = neon.vld1q_f32(&b);

    const result = neon.vaddq_f32(va, vb);

    var output: [LANES]f32 = undefined;
    neon.vst1q_f32(&output, result);

    try std.testing.expectEqualSlices(
        f32,
        &[_]f32{
            11.0,
            22.0,
            33.0,
            44.0,
        },
        &output,
    );
}

test "zeon vector multiply works for wave lanes" {
    const a: [LANES]f32 = .{
        1.0,
        2.0,
        3.0,
        4.0,
    };

    const b: [LANES]f32 = .{
        2.0,
        3.0,
        4.0,
        5.0,
    };

    const va = neon.vld1q_f32(&a);
    const vb = neon.vld1q_f32(&b);

    const result = neon.vmulq_f32(va, vb);

    var output: [LANES]f32 = undefined;
    neon.vst1q_f32(&output, result);

    try std.testing.expectEqualSlices(
        f32,
        &[_]f32{
            2.0,
            6.0,
            12.0,
            20.0,
        },
        &output,
    );
}

test "zeon vector scalar multiply works for wave lanes" {
    const input: [LANES]f32 = .{
        1.0,
        2.0,
        3.0,
        4.0,
    };

    const vector = neon.vld1q_f32(&input);
    const result = neon.vmulq_n_f32(
        vector,
        0.125,
    );

    var output: [LANES]f32 = undefined;
    neon.vst1q_f32(&output, result);

    try std.testing.expectEqualSlices(
        f32,
        &[_]f32{
            0.125,
            0.25,
            0.375,
            0.5,
        },
        &output,
    );
}

test "zeon vector max clamps wave values" {
    const input: [LANES]f32 = .{
        -1.0,
        0.25,
        0.75,
        2.0,
    };

    const vector = neon.vld1q_f32(&input);

    const result = neon.vmaxq_f32(
        vector,
        neon.vmovq_n_f32(0.0),
    );

    var output: [LANES]f32 = undefined;
    neon.vst1q_f32(&output, result);

    try std.testing.expectEqualSlices(
        f32,
        &[_]f32{
            0.0,
            0.25,
            0.75,
            2.0,
        },
        &output,
    );
}

test "zeon vector min clamps wave values" {
    const input: [LANES]f32 = .{
        -1.0,
        0.25,
        0.75,
        2.0,
    };

    const vector = neon.vld1q_f32(&input);

    const result = neon.vminq_f32(
        vector,
        neon.vmovq_n_f32(1.0),
    );

    var output: [LANES]f32 = undefined;
    neon.vst1q_f32(&output, result);

    try std.testing.expectEqualSlices(
        f32,
        &[_]f32{
            -1.0,
            0.25,
            0.75,
            1.0,
        },
        &output,
    );
}

test "render4 produces finite RGB values" {
    const fx: [LANES]f32 = .{
        -1.0,
        -0.33333334,
        0.33333334,
        1.0,
    };

    var red: [LANES]f32 = undefined;
    var green: [LANES]f32 = undefined;
    var blue: [LANES]f32 = undefined;

    render4(
        &fx,
        0.0,
        1.0,
        &red,
        &green,
        &blue,
    );

    for (0..LANES) |i| {
        try std.testing.expect(std.math.isFinite(red[i]));
        try std.testing.expect(std.math.isFinite(green[i]));
        try std.testing.expect(std.math.isFinite(blue[i]));

        try std.testing.expect(red[i] >= 0.0);
        try std.testing.expect(green[i] >= 0.0);
        try std.testing.expect(blue[i] >= 0.0);

        try std.testing.expect(red[i] <= 255.0);
        try std.testing.expect(green[i] <= 255.0);
        try std.testing.expect(blue[i] <= 255.0);
    }
}

test "render4 is deterministic" {
    const fx: [LANES]f32 = .{
        -0.8,
        -0.2,
        0.2,
        0.8,
    };

    var r1: [LANES]f32 = undefined;
    var g1: [LANES]f32 = undefined;
    var b1: [LANES]f32 = undefined;

    var r2: [LANES]f32 = undefined;
    var g2: [LANES]f32 = undefined;
    var b2: [LANES]f32 = undefined;

    render4(
        &fx,
        0.35,
        2.0,
        &r1,
        &g1,
        &b1,
    );

    render4(
        &fx,
        0.35,
        2.0,
        &r2,
        &g2,
        &b2,
    );

    try std.testing.expectEqualSlices(f32, &r1, &r2);
    try std.testing.expectEqualSlices(f32, &g1, &g2);
    try std.testing.expectEqualSlices(f32, &b1, &b2);
}
