name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig-version: [0.13.0]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Darling
        run: |
          sudo apt install cmake automake clang-15 bison flex libfuse-dev libudev-dev pkg-config libc6-dev-i386 \
            gcc-multilib libcairo2-dev libgl1-mesa-dev curl libglu1-mesa-dev libtiff5-dev \
            libfreetype6-dev git git-lfs libelf-dev libxml2-dev libegl1-mesa-dev libfontconfig1-dev \
            libbsd-dev libxrandr-dev libxcursor-dev libgif-dev libavutil-dev libpulse-dev \
            libavformat-dev libavcodec-dev libswresample-dev libdbus-1-dev libxkbfile-dev \
            libssl-dev libstdc++-12-dev
          git clone --recursive https://github.com/darlinghq/darling.git
          cd darling && mkdir build && cd build
          cmake ..
          make
          sudo make install
          make lkm
          sudo make lkm_install
          ls

      - name: Install QEMU User-Mode
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user qemu-user-static

          echo

          echo aarch64:
          qemu-aarch64 -version
          echo

          echo arm:
          qemu-arm -version
          echo

          echo aarch64_be:
          qemu-aarch64_be -version

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - name: Build and Test
        run: |
          zig build test \
            -fqemu \
            -freference-trace \
            --summary all
