name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig-version: [0.13.0]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install QEMU User-Mode
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user

          echo

          echo aarch64:
          qemu-aarch64 -version
          echo

          echo arm:
          qemu-arm -version
          echo

          echo aarch64_be:
          qemu-aarch64_be -version

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - name: Build and Test
        run: |
          make test
          DEBUG=1 make test
